CD /D E:\原神多服创建工具GIMS\GIMS\
CHCP 65001
XCOPY /E /Y "SeaRes_V3.5.0\" "E:\GenshinImpactNew\Seaserver"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Persistent" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Persistent"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Resources" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Resources"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\SDKCaches" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\SDKCaches"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Managed\Resources" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Managed\Resources"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Native\Data\Resources" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Native\Data\Resources"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Native\Data\etc" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Native\Data\etc"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\locales" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\locales"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\AssetBundles" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\AssetBundles"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\Audio" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\Audio"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\Chroma" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\Chroma"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\hdiff" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\hdiff"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\kcp" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\kcp"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\MiHoYoSDKRes" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\MiHoYoSDKRes"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\Persistent" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\Persistent"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\VideoAssets" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\VideoAssets"
MKLINK /D "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\xlua" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\xlua"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\blueReporter.exe" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\blueReporter.exe"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\boot.config" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\boot.config"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\level0" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\level0"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\level1" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\level1"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\level2" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\level2"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\level3" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\level3"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\level4" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\level4"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\level5" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\level5"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\resources.assets" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\resources.assets"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\resources.assets.resS" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\resources.assets.resS"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\sharedassets0.assets" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\sharedassets0.assets"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\sharedassets0.assets.resS" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\sharedassets0.assets.resS"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\sharedassets1.assets" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\sharedassets1.assets"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\sharedassets2.assets" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\sharedassets2.assets"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\sharedassets3.assets" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\sharedassets3.assets"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\sharedassets4.assets" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\sharedassets4.assets"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\sharedassets5.assets" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\sharedassets5.assets"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\strings.csv" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\strings.csv"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\Astrolabe.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\Astrolabe.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\MiHoYoMTRSDK.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\MiHoYoMTRSDK.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\MiHoYoSDKUploader.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\MiHoYoSDKUploader.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\Rewired_DirectInput.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\Rewired_DirectInput.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\Telemetry.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\Telemetry.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\ThirdPartyNotices.txt" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\ThirdPartyNotices.txt"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\ZFEmbedWeb.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\ZFEmbedWeb.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\ZFGameBrowser.exe" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\ZFGameBrowser.exe"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\ZFProxyWeb.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\ZFProxyWeb.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\chrome_100_percent.pak" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\chrome_100_percent.pak"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\chrome_200_percent.pak" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\chrome_200_percent.pak"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\chrome_elf.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\chrome_elf.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\crashreport.exe" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\crashreport.exe"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\icudtl.dat" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\icudtl.dat"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\kcp.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\kcp.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\libEGL.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\libEGL.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\libGLESv2.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\libGLESv2.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\libUbiCustomEvent.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\libUbiCustomEvent.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\mailbox.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\mailbox.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\resources.pak" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\resources.pak"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\snapshot_blob.bin" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\snapshot_blob.bin"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\v8_context_snapshot.bin" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\v8_context_snapshot.bin"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\vk_swiftshader.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\vk_swiftshader.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\vk_swiftshader_icd.json" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\vk_swiftshader_icd.json"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\vulkan-1.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\vulkan-1.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\Plugins\zf_cef.dll" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\Plugins\zf_cef.dll"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\asb_settings.json" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\asb_settings.json"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\ctable_streaming.dat" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\ctable_streaming.dat"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\data_versions_streaming" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\data_versions_streaming"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\hardware_model_config.json" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\hardware_model_config.json"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\res_versions_streaming" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\res_versions_streaming"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\silence_versions_streaming" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\silence_versions_streaming"
MKLINK "E:\GenshinImpactNew\Seaserver\GenshinImpact_Data\StreamingAssets\svc_catalog" "E:\Genshin Impact\Genshin Impact game\YuanShen_Data\StreamingAssets\svc_catalog"
COPY /Y "config.ini" "E:\GenshinImpactNew\Seaserver\config.ini"
DEL /Q "config.ini"
COPY /Y "cfg.ini" "cfg\cfg.ini"
DEL /Q "cfg.ini"
mshta VBScript:Execute("Set a=CreateObject(""WScript.Shell""):Set b=a.CreateShortcut(a.SpecialFolders(""Desktop"") & ""\International.lnk""):b.TargetPath=""E:\GenshinImpactNew\Seaserver\GenshinImpact.exe"":b.WorkingDirectory=""E:\GenshinImpactNew\Seaserver"":b.Save:close")
PAUSE
